export const REGIONS = {
  quadril: {
    slug: "quadril",
    name: "Quadril",
    navSubtitle: "Ortopedia, quadril",
    whatsappSubject: "dor no quadril",
    bioFocusCopy: "Se a dor no quadril está dificultando caminhar, levantar da cadeira ou dormir de lado, a avaliação ajuda a entender a causa e definir o próximo passo com segurança.",
    title: "Ortopedista para Quadril em Brasília | Dr. Luiz Sarmanho",
    description: "Avaliação ortopédica para dor no quadril, artrose, bursite, dor na virilha, limitação para caminhar e artroplastia. Agende com o Dr. Luiz Sarmanho em Brasília.",
    heroTitle: "Avaliação para <span class=\"hero-title-accent\">dor no quadril</span>, artrose e limitação para caminhar",
    heroCopy: "Dor na virilha, dor lateral do quadril, rigidez para levantar ou dificuldade para caminhar precisam de uma avaliação bem direcionada. O Dr. Luiz Sarmanho atua com ortopedia, cirurgia do quadril, artroplastia e procedimentos para controle da dor.",
    proofFocus: "Foco em quadril, artrose e mobilidade",
    symptomsTitle: "Você reconhece algum desses sinais no quadril?",
    symptomsCopy: "A dor no quadril pode aparecer na virilha, na lateral, no glúteo ou irradiar para a coxa. A localização e o padrão da dor ajudam a diferenciar articulação, tendões, bursas e coluna.",
    symptoms: [
      { icon: "leg", title: "Dor na virilha", desc: "Dor profunda que piora ao caminhar, entrar no carro, cruzar as pernas ou calçar sapatos." },
      { icon: "walking", title: "Dificuldade para caminhar", desc: "Limitação progressiva para andar, subir rampas, ficar em pé ou manter atividades simples." },
      { icon: "pain-burst", title: "Dor lateral ao deitar", desc: "Incômodo para dormir de lado, subir escadas ou apoiar peso sobre a perna." },
      { icon: "joints", title: "Rigidez ao levantar", desc: "Sensação de travamento ao sair da cadeira, da cama ou após ficar muito tempo sentado." },
      { icon: "xray", title: "Artrose ou desgaste", desc: "Desgaste articular com dor, perda de mobilidade e impacto crescente na rotina." },
      { icon: "trauma-alert", title: "Dor após queda ou impacto", desc: "Piora depois de trauma, torção, esforço ou aumento repentino de carga." },
    ],
    causesTitle: "O que pode estar por trás da dor no quadril",
    causesCopy: "A avaliação clínica ajuda a separar quadros articulares, tendíneos, inflamatórios e dores referidas da coluna.",
    causes: [
      { icon: "xray", title: "Artrose do quadril", desc: "Desgaste da articulação, geralmente associado a dor na virilha, rigidez e perda de mobilidade." },
      { icon: "pain", title: "Bursite trocantérica", desc: "Dor na lateral do quadril, comum ao deitar de lado ou caminhar por mais tempo." },
      { icon: "health-data-sync", title: "Tendinopatias glúteas", desc: "Alterações nos tendões laterais que podem gerar dor e perda de força." },
      { icon: "joints", title: "Impacto ou lesão labral", desc: "Alterações internas que podem causar dor profunda, estalos ou sensação de bloqueio." },
      { icon: "crutches", title: "Fraturas e sequelas de trauma", desc: "Casos após queda, impacto ou piora súbita precisam de avaliação cuidadosa." },
      { icon: "medical-search", title: "Dor referida da coluna", desc: "Alguns sintomas no quadril podem ter origem lombar ou neurológica." },
    ],
    proceduresTitle: "Condutas e procedimentos para dor no quadril",
    proceduresCopy: "O plano depende do diagnóstico, do grau de limitação e dos exames. A proposta é indicar o caminho mais adequado para cada caso.",
    procedures: [
      { icon: "doctor", title: "Avaliação ortopédica do quadril", desc: "História da dor, exame físico, análise da marcha, mobilidade e exames já realizados." },
      { icon: "injection-care", title: "Procedimentos para dor", desc: "Infiltrações e procedimentos podem ser avaliados quando houver indicação clínica." },
      { icon: "health-worker-form", title: "Tratamento conservador", desc: "Orientação sobre medicação, fisioterapia, ajustes de carga e acompanhamento." },
      { icon: "xray", title: "Discussão sobre artroplastia", desc: "Quando a artrose é avançada, a cirurgia pode ser discutida com clareza e critério." },
    ],
    when: ["Dor no quadril por mais de 1 a 2 semanas", "Dor ao caminhar, subir escadas ou levantar da cadeira", "Dor na virilha ou perda de mobilidade", "Dor ao deitar de lado", "Piora após queda ou trauma", "Diagnóstico prévio de artrose com limitação crescente"],
    faq: [
      { q: "Dor na virilha pode ser do quadril?", a: "Pode. Dor profunda na virilha é uma apresentação comum de alterações articulares do quadril, mas a confirmação depende da avaliação." },
      { q: "Toda dor no quadril é artrose?", a: "Não. Bursites, tendinopatias, impacto, lesões e dor referida da coluna também podem causar sintomas." },
      { q: "Quando a artroplastia deve ser considerada?", a: "A artroplastia pode ser discutida quando há desgaste avançado, dor persistente e limitação importante, sempre após avaliação individual." },
      { q: "Infiltração pode ajudar dor no quadril?", a: "Em casos selecionados, procedimentos para dor podem ser avaliados conforme diagnóstico e indicação clínica." },
      { q: "Preciso levar exames?", a: "Se tiver radiografias, ressonância ou exames anteriores, leve para a consulta. Eles ajudam na avaliação." },
    ],
    finalCta: "Não deixe a dor no quadril reduzir sua mobilidade.",
  },
  joelho: {
    slug: "joelho",
    name: "Joelho",
    navSubtitle: "Ortopedia, joelho",
    whatsappSubject: "dor no joelho",
    bioFocusCopy: "Se o joelho dói ao subir escadas, agachar, caminhar ou fica inchado, a consulta ajuda a entender a causa e orientar o próximo passo com segurança.",
    title: "Ortopedista para Joelho em Brasília | Dr. Luiz Sarmanho",
    description: "Avaliação ortopédica para dor no joelho, artrose, estalos, inchaço, falseio, lesões e limitação para caminhar. Agende com o Dr. Luiz Sarmanho.",
    heroTitle: "Avaliação para <span class=\"hero-title-accent\">dor no joelho</span>, estalos, inchaço e desgaste",
    heroCopy: "Dor ao subir escadas, agachar, caminhar ou levantar da cadeira pode indicar sobrecarga, lesão, artrose ou inflamação. Uma avaliação direcionada ajuda a definir o melhor caminho antes que a limitação avance.",
    proofFocus: "Foco em dor, função e retorno à rotina",
    symptomsTitle: "Você reconhece algum desses sinais no joelho?",
    symptomsCopy: "O joelho costuma avisar quando algo está errado: dor, inchaço, estalos, rigidez ou insegurança para apoiar o peso merecem atenção.",
    symptoms: [
      { icon: "walking", title: "Dor ao caminhar", desc: "Dor que aparece em caminhadas curtas, descidas, rampas ou após ficar muito tempo em pé." },
      { icon: "joints", title: "Estalos ou crepitação", desc: "Sensação de atrito, areia, estalos ou ruídos ao dobrar e esticar o joelho." },
      { icon: "pain-burst", title: "Dor ao subir escadas", desc: "Desconforto na frente, laterais ou parte interna do joelho ao mudar de degrau." },
      { icon: "trauma-alert", title: "Falseio ou insegurança", desc: "Joelho que parece ceder, falhar ou ficar instável durante movimentos." },
      { icon: "xray", title: "Inchaço ou rigidez", desc: "Aumento de volume, calor local ou dificuldade para dobrar e esticar." },
      { icon: "crutches", title: "Dor após trauma", desc: "Sintomas depois de torção, queda, pancada, esporte ou esforço repentino." },
    ],
    causesTitle: "O que pode estar por trás da dor no joelho",
    causesCopy: "O diagnóstico correto depende de exame físico, história da dor e, quando necessário, exames de imagem.",
    causes: [
      { icon: "xray", title: "Artrose e desgaste", desc: "Desgaste da cartilagem que pode causar dor mecânica, rigidez e limitação progressiva." },
      { icon: "joints", title: "Lesões de menisco", desc: "Podem causar dor localizada, estalos, sensação de travamento ou piora ao agachar." },
      { icon: "trauma-alert", title: "Lesões ligamentares", desc: "Entorses e rupturas que causam inchaço, instabilidade e insegurança para apoiar." },
      { icon: "health-data-sync", title: "Tendinites e sobrecarga", desc: "Dor relacionada a treino, trabalho, excesso de carga ou retorno rápido à atividade." },
      { icon: "pain", title: "Dor femoropatelar", desc: "Dor anterior que costuma piorar em escadas, agachamentos ou longos períodos sentado." },
      { icon: "medical-search", title: "Bursites e inflamações", desc: "Processos inflamatórios que podem causar dor pontual, inchaço e sensibilidade." },
    ],
    proceduresTitle: "Condutas e procedimentos para dor no joelho",
    proceduresCopy: "O objetivo é entender a causa da dor e indicar tratamento conservador, procedimento ou cirurgia apenas quando fizer sentido.",
    procedures: [
      { icon: "doctor", title: "Avaliação ortopédica do joelho", desc: "Exame de estabilidade, meniscos, mobilidade, marcha e análise de exames." },
      { icon: "health-worker-form", title: "Plano conservador", desc: "Orientação sobre controle da dor, fortalecimento, fisioterapia e ajuste de atividades." },
      { icon: "injection-care", title: "Procedimentos para dor", desc: "Infiltrações e outros procedimentos podem ser avaliados em casos selecionados." },
      { icon: "medical-records", title: "Acompanhamento da evolução", desc: "Reavaliação conforme resposta ao tratamento e impacto na rotina." },
    ],
    when: ["Dor por mais de 1 a 2 semanas", "Joelho inchado, quente ou rígido", "Falseio, bloqueio ou travamento", "Dor para subir escadas ou agachar", "Dor que limita esporte, trabalho ou caminhada", "Trauma recente com dor intensa ou perda de movimento"],
    faq: [
      { q: "Toda dor no joelho precisa de cirurgia?", a: "Não. Muitos quadros podem ser tratados de forma conservadora, com reabilitação, orientação e procedimentos quando indicados." },
      { q: "Estalos no joelho são preocupantes?", a: "Estalos isolados podem não ser graves, mas quando vêm com dor, inchaço ou bloqueio precisam de avaliação." },
      { q: "Dor ao subir escadas pode ser artrose?", a: "Pode ser artrose, dor femoropatelar, sobrecarga ou outras causas. O exame ajuda a diferenciar." },
      { q: "Infiltração no joelho é para todos os casos?", a: "Não. A indicação depende do diagnóstico, sintomas, exames e objetivo do tratamento." },
      { q: "Preciso parar de caminhar?", a: "A orientação depende do quadro. A consulta ajuda a definir ajustes temporários e retorno gradual." },
    ],
    finalCta: "Não deixe a dor no joelho limitar seus passos.",
  },
  coluna: {
    slug: "coluna",
    name: "Coluna",
    navSubtitle: "Ortopedia, coluna",
    whatsappSubject: "dor na coluna",
    bioFocusCopy: "Se a dor na coluna trava seus movimentos, desce para o braço ou para a perna, ou vem com formigamento, a avaliação ajuda a identificar a origem do problema.",
    title: "Ortopedista para Coluna em Brasília | Dr. Luiz Sarmanho",
    description: "Avaliação para dor na coluna, lombalgia, cervicalgia, dor irradiada, formigamento, travamento e suspeita de hérnia. Agende com o Dr. Luiz Sarmanho.",
    heroTitle: "Avaliação para <span class=\"hero-title-accent\">dor na coluna</span>, travamento e dor irradiada",
    heroCopy: "Dor lombar, cervical, formigamento ou dor que desce para braço ou perna precisam de avaliação para entender se a origem é muscular, articular, discal ou neurológica.",
    proofFocus: "Foco em diagnóstico e controle da dor",
    symptomsTitle: "Você reconhece algum desses sinais na coluna?",
    symptomsCopy: "A dor na coluna pode ser localizada ou irradiada. O padrão de piora, a duração e os sintomas associados ajudam a orientar a conduta.",
    symptoms: [
      { icon: "pain-burst", title: "Dor lombar", desc: "Dor na parte baixa das costas ao sentar, levantar, carregar peso ou ficar muito tempo em pé." },
      { icon: "walking", title: "Dor descendo para a perna", desc: "Dor, choque, peso ou formigamento em glúteo, coxa, panturrilha ou pé." },
      { icon: "crutches", title: "Travamento", desc: "Crises com dificuldade para endireitar o corpo, levantar ou caminhar." },
      { icon: "medical-search", title: "Dor cervical", desc: "Dor no pescoço, rigidez, tensão e desconforto ao virar a cabeça." },
      { icon: "leg", title: "Formigamento ou dormência", desc: "Alterações de sensibilidade que podem indicar irritação de estruturas nervosas." },
      { icon: "trauma-alert", title: "Dor após esforço", desc: "Piora depois de treino, trabalho físico, postura prolongada, queda ou impacto." },
    ],
    causesTitle: "O que pode estar por trás da dor na coluna",
    causesCopy: "A dor pode ter origem muscular, articular, discal, postural ou neurológica. A avaliação evita tratar sintomas sem entender a causa.",
    causes: [
      { icon: "health-data-sync", title: "Lombalgia mecânica", desc: "Dor relacionada a sobrecarga, postura, esforço físico ou desequilíbrio muscular." },
      { icon: "xray", title: "Hérnia ou protrusão discal", desc: "Alterações no disco que podem irritar nervos e causar dor irradiada." },
      { icon: "joints", title: "Artrose facetária", desc: "Desgaste nas articulações da coluna, comum em dor crônica e rigidez." },
      { icon: "pain", title: "Ciatalgia", desc: "Dor irradiada para a perna, frequentemente associada à irritação do nervo ciático." },
      { icon: "medical-records", title: "Cervicalgia", desc: "Dor no pescoço associada a tensão, postura, degeneração ou sobrecarga." },
      { icon: "medical-search", title: "Alterações degenerativas", desc: "Mudanças estruturais que podem gerar dor recorrente ou limitação." },
    ],
    proceduresTitle: "Condutas e procedimentos para dor na coluna",
    proceduresCopy: "Em casos selecionados, procedimentos para dor podem ser discutidos junto a medidas conservadoras e reabilitação.",
    procedures: [
      { icon: "doctor", title: "Avaliação ortopédica da coluna", desc: "História clínica, exame físico, rastreio neurológico básico e análise de exames." },
      { icon: "health-worker-form", title: "Plano conservador", desc: "Orientação sobre medicação, fisioterapia, ergonomia e retorno progressivo." },
      { icon: "injection-care", title: "Procedimentos para dor", desc: "Bloqueios ou infiltrações podem ser avaliados quando houver indicação clínica." },
      { icon: "medical-search", title: "Investigação de dor irradiada", desc: "Avaliação de sintomas que descem para braço ou perna e impactam a rotina." },
    ],
    when: ["Dor na coluna por mais de 1 a 2 semanas", "Dor descendo para braço ou perna", "Formigamento, dormência ou perda de força", "Crises recorrentes de travamento", "Dor que piora ao sentar, deitar ou levantar", "Dor após trauma, queda ou esforço importante"],
    faq: [
      { q: "Dor na coluna sempre é hérnia de disco?", a: "Não. Sobrecarga muscular, alterações articulares, postura, artrose e outras causas também podem gerar dor." },
      { q: "Dor descendo para a perna pode ser ciático?", a: "Pode estar relacionada à irritação de estruturas nervosas, mas a confirmação depende de avaliação." },
      { q: "Preciso de ressonância?", a: "Nem sempre. A necessidade de exame depende dos sintomas, evolução e achados da consulta." },
      { q: "Toda dor na coluna precisa de cirurgia?", a: "Não. Muitos casos são conduzidos com tratamento conservador e procedimentos quando indicados." },
      { q: "Quando devo procurar atendimento?", a: "Quando a dor persiste, limita sua rotina, irradia ou vem acompanhada de formigamento." },
    ],
    finalCta: "Não deixe a dor na coluna comandar sua rotina.",
  },
  ombro: {
    slug: "ombro",
    name: "Ombro",
    navSubtitle: "Ortopedia, ombro",
    whatsappSubject: "dor no ombro",
    bioFocusCopy: "Se levantar o braço, dormir de lado, vestir roupa ou carregar peso virou incômodo, a avaliação do ombro ajuda a entender a causa da dor.",
    title: "Ortopedista para Ombro em Brasília | Dr. Luiz Sarmanho",
    description: "Avaliação para dor no ombro, tendinite, bursite, manguito rotador, rigidez, perda de força e dor ao levantar o braço. Agende com o Dr. Luiz Sarmanho.",
    heroTitle: "Avaliação para <span class=\"hero-title-accent\">dor no ombro</span>, perda de força e limitação de movimento",
    heroCopy: "Dor ao levantar o braço, vestir roupa, dormir de lado ou carregar peso pode estar ligada a tendões, bursas, articulações ou trauma. A avaliação direciona o tratamento com mais precisão.",
    proofFocus: "Foco em mobilidade e função do braço",
    symptomsTitle: "Você reconhece algum desses sinais no ombro?",
    symptomsCopy: "A dor no ombro costuma limitar movimentos do dia a dia e pode piorar à noite ou após esforço.",
    symptoms: [
      { icon: "health-worker-form", title: "Dor ao levantar o braço", desc: "Desconforto ao pegar objetos no alto, vestir roupas ou pentear o cabelo." },
      { icon: "pain-burst", title: "Dor para dormir de lado", desc: "Incômodo ao apoiar o ombro no travesseiro ou mudar de posição durante a noite." },
      { icon: "crutches", title: "Perda de força", desc: "Dificuldade para carregar peso, empurrar, puxar ou sustentar o braço." },
      { icon: "joints", title: "Rigidez", desc: "Limitação para alcançar as costas, girar o braço ou completar movimentos." },
      { icon: "trauma-alert", title: "Dor após queda ou treino", desc: "Sintomas após trauma, academia, esporte ou movimentos repetitivos." },
      { icon: "medical-search", title: "Dor irradiando para o braço", desc: "Desconforto que desce pelo braço e pode confundir a origem do problema." },
    ],
    causesTitle: "O que pode estar por trás da dor no ombro",
    causesCopy: "O ombro tem muitas estruturas envolvidas. O exame físico ajuda a diferenciar tendões, bursas, articulação e instabilidade.",
    causes: [
      { icon: "pain", title: "Tendinite e bursite", desc: "Inflamações associadas a sobrecarga, repetição ou alterações biomecânicas." },
      { icon: "health-data-sync", title: "Manguito rotador", desc: "Alterações nos tendões responsáveis por força, estabilidade e movimento." },
      { icon: "joints", title: "Síndrome do impacto", desc: "Dor provocada por atrito de estruturas internas em determinados movimentos." },
      { icon: "crutches", title: "Capsulite adesiva", desc: "Rigidez progressiva com dor e perda importante de movimento." },
      { icon: "trauma-alert", title: "Instabilidade ou luxação", desc: "Sensação de que o ombro pode sair do lugar, principalmente após trauma." },
      { icon: "xray", title: "Artrose e desgaste", desc: "Alterações degenerativas que podem causar dor, rigidez e limitação." },
    ],
    proceduresTitle: "Condutas e procedimentos para dor no ombro",
    proceduresCopy: "O tratamento depende da causa, do grau de limitação e da resposta a medidas iniciais.",
    procedures: [
      { icon: "doctor", title: "Avaliação ortopédica do ombro", desc: "Testes de mobilidade, força, impacto, instabilidade e análise de exames." },
      { icon: "health-worker-form", title: "Reabilitação orientada", desc: "Conduta alinhada ao diagnóstico, com retorno gradual à função." },
      { icon: "injection-care", title: "Procedimentos para dor", desc: "Infiltrações podem ser avaliadas em bursas, tendões ou articulação quando indicadas." },
      { icon: "medical-records", title: "Acompanhamento", desc: "Reavaliação da dor, mobilidade e necessidade de novos exames." },
    ],
    when: ["Dor no ombro por mais de 1 a 2 semanas", "Dificuldade para levantar o braço", "Dor noturna frequente", "Perda de força ou sensação de braço pesado", "Trauma, queda ou episódio de luxação", "Dor que limita trabalho, esporte ou rotina"],
    faq: [
      { q: "Dor no ombro pode ser tendinite ou bursite?", a: "Pode. São causas comuns, mas a confirmação depende da avaliação clínica." },
      { q: "Toda lesão do manguito precisa operar?", a: "Não. A conduta depende do tipo de lesão, idade, função, dor e resposta ao tratamento." },
      { q: "Dor noturna no ombro é comum?", a: "Pode ocorrer em tendinites, bursites e outras condições. Se for frequente, vale avaliar." },
      { q: "Infiltração ajuda dor no ombro?", a: "Em casos selecionados, pode ser considerada conforme diagnóstico e indicação clínica." },
      { q: "Preciso levar exames?", a: "Se tiver exames anteriores, leve. Caso necessário, novos exames podem ser solicitados." },
    ],
    finalCta: "Não deixe a dor no ombro limitar seus movimentos.",
  },
  "mao-punho": {
    slug: "mao-punho",
    bioFocusCopy: "Se formigamento, perda de força ou dor na mão e no punho estão atrapalhando trabalho, sono ou tarefas simples, a avaliação direciona o cuidado.",
    name: "Mão e Punho",
    navSubtitle: "Ortopedia, mão e punho",
    whatsappSubject: "dor na mão ou punho",
    title: "Ortopedista para Mão e Punho em Brasília | Dr. Luiz Sarmanho",
    description: "Avaliação para dor na mão e punho, formigamento, túnel do carpo, tendinites, dedo em gatilho, cisto e perda de força. Agende com o Dr. Luiz Sarmanho.",
    heroTitle: "Avaliação para <span class=\"hero-title-accent\">dor na mão e punho</span>, formigamento e perda de força",
    heroCopy: "Dor ao digitar, formigamento nos dedos, perda de força ou punho dolorido podem indicar compressão nervosa, tendinite, sobrecarga ou lesão. A avaliação ajuda a identificar a origem e orientar a conduta.",
    proofFocus: "Foco em função, força e atividades manuais",
    symptomsTitle: "Você reconhece algum desses sinais na mão ou punho?",
    symptomsCopy: "Sintomas nessa região atrapalham trabalho, celular, digitação, treino, sono e tarefas simples. Quanto mais específica a queixa, melhor o direcionamento da avaliação.",
    symptoms: [
      { icon: "pain-burst", title: "Formigamento nos dedos", desc: "Dormência, choque ou perda de sensibilidade, principalmente à noite." },
      { icon: "health-worker-form", title: "Dor ao digitar ou usar celular", desc: "Incômodo em atividades repetitivas, mouse, escrita, ferramentas ou instrumentos." },
      { icon: "crutches", title: "Perda de força", desc: "Dificuldade para segurar objetos, abrir potes ou carregar peso." },
      { icon: "joints", title: "Dedo travando", desc: "Estalo doloroso ou dedo que prende ao dobrar e esticar." },
      { icon: "xray", title: "Caroço ou inchaço", desc: "Nódulo, cisto ou aumento de volume no punho ou na mão." },
      { icon: "trauma-alert", title: "Dor após queda", desc: "Dor persistente depois de impacto, torção ou apoio com a mão." },
    ],
    causesTitle: "O que pode estar por trás da dor na mão ou punho",
    causesCopy: "Mãos e punhos têm estruturas pequenas e próximas. Avaliar nervos, tendões e articulações evita condutas genéricas.",
    causes: [
      { icon: "medical-search", title: "Síndrome do túnel do carpo", desc: "Compressão nervosa associada a formigamento, dormência e perda de força." },
      { icon: "health-data-sync", title: "Tendinites e tenossinovites", desc: "Inflamações de tendões relacionadas a repetição, esforço ou sobrecarga." },
      { icon: "joints", title: "Dedo em gatilho", desc: "Travamento ou estalo doloroso ao movimentar o dedo." },
      { icon: "xray", title: "Cisto sinovial", desc: "Nódulo comum no punho ou mão, que pode gerar dor ou incômodo funcional." },
      { icon: "pain", title: "Artrose nas mãos", desc: "Desgaste que pode causar dor, rigidez e deformidades progressivas." },
      { icon: "trauma-alert", title: "Lesões traumáticas", desc: "Alterações após quedas, impactos, torções ou esforço intenso." },
    ],
    proceduresTitle: "Condutas para dor na mão e punho",
    proceduresCopy: "A conduta depende da estrutura envolvida e do impacto funcional na rotina do paciente.",
    procedures: [
      { icon: "doctor", title: "Avaliação da mão e punho", desc: "Exame de força, sensibilidade, mobilidade, tendões e articulações." },
      { icon: "medical-search", title: "Investigação de formigamento", desc: "Avaliação de compressões nervosas e sintomas noturnos." },
      { icon: "health-worker-form", title: "Tratamento conservador", desc: "Orientação sobre imobilização, medicação, fisioterapia e ajustes de atividade." },
      { icon: "injection-care", title: "Procedimentos quando indicados", desc: "Infiltrações podem ser avaliadas para tendões, articulações ou estruturas específicas." },
    ],
    when: ["Formigamento frequente nos dedos", "Dor no punho ou mão por mais de 1 a 2 semanas", "Perda de força ou queda de objetos", "Dedo travando ou estalando", "Nódulo, cisto ou inchaço", "Dor após queda, trauma ou esforço repetitivo"],
    faq: [
      { q: "Formigamento pode ser túnel do carpo?", a: "Pode, especialmente se piora à noite ou atinge alguns dedos, mas a avaliação é necessária." },
      { q: "Dor ao digitar é tendinite?", a: "Pode estar relacionada a tendinites, sobrecarga ou outras alterações. O diagnóstico depende do exame." },
      { q: "Dedo travando precisa avaliar?", a: "Sim. O dedo em gatilho pode evoluir com mais dor e limitação." },
      { q: "Cisto no punho é perigoso?", a: "Muitos são benignos, mas devem ser avaliados se causam dor, crescimento ou limitação." },
      { q: "Preciso parar de trabalhar com a mão?", a: "Depende do diagnóstico. A consulta ajuda a definir ajustes temporários e tratamento." },
    ],
    finalCta: "Não deixe a dor na mão ou punho limitar suas atividades.",
  },
  "pe-tornozelo": {
    slug: "pe-tornozelo",
    bioFocusCopy: "Se pisar, caminhar, treinar ou trabalhar em pé está difícil por dor no pé ou tornozelo, a avaliação ajuda a identificar a causa e evitar recorrências.",
    name: "Pé e Tornozelo",
    navSubtitle: "Ortopedia, pé e tornozelo",
    whatsappSubject: "dor no pé ou tornozelo",
    title: "Ortopedista para Pé e Tornozelo em Brasília | Dr. Luiz Sarmanho",
    description: "Avaliação para dor no pé e tornozelo, fascite plantar, esporão, entorse, tendinites, instabilidade e dor ao pisar. Agende com o Dr. Luiz Sarmanho.",
    heroTitle: "Avaliação para <span class=\"hero-title-accent\">dor no pé e tornozelo</span>, entorse e dor ao pisar",
    heroCopy: "Dor ao pisar, dor no calcanhar, tornozelo inchado ou torções repetidas podem comprometer caminhada, trabalho e treino. A avaliação ajuda a identificar a causa e evitar recorrências.",
    proofFocus: "Foco em pisada, mobilidade e retorno à rotina",
    symptomsTitle: "Você reconhece algum desses sinais no pé ou tornozelo?",
    symptomsCopy: "Pé e tornozelo sustentam carga o dia inteiro. Dor persistente, instabilidade ou inchaço merecem avaliação direcionada.",
    symptoms: [
      { icon: "foot", title: "Dor ao pisar", desc: "Incômodo nos primeiros passos, depois de caminhar ou após ficar muito tempo em pé." },
      { icon: "walking", title: "Dor no calcanhar", desc: "Dor ao acordar, apoiar peso ou caminhar, especialmente na sola ou atrás do pé." },
      { icon: "trauma-alert", title: "Torções repetidas", desc: "Sensação de instabilidade e insegurança em pisos irregulares." },
      { icon: "pain-burst", title: "Inchaço no tornozelo", desc: "Aumento de volume após esforço, torção ou ao fim do dia." },
      { icon: "crutches", title: "Dor no tendão de Aquiles", desc: "Incômodo atrás do tornozelo ao correr, subir escadas ou iniciar movimentos." },
      { icon: "joints", title: "Rigidez ou travamento", desc: "Dificuldade para movimentar o tornozelo ou adaptar a pisada." },
    ],
    causesTitle: "O que pode estar por trás da dor no pé ou tornozelo",
    causesCopy: "A dor pode envolver fáscia plantar, tendões, ligamentos, articulações, ossos ou sobrecarga da pisada.",
    causes: [
      { icon: "foot", title: "Fascite plantar", desc: "Dor na sola do pé ou no calcanhar, comum nos primeiros passos do dia." },
      { icon: "xray", title: "Esporão de calcâneo", desc: "Alteração óssea frequentemente associada a dor plantar e sobrecarga local." },
      { icon: "trauma-alert", title: "Entorse de tornozelo", desc: "Lesão ligamentar após torção, podendo gerar dor, inchaço e instabilidade." },
      { icon: "health-data-sync", title: "Tendinites", desc: "Dor em tendões do pé e tornozelo por repetição, treino ou esforço." },
      { icon: "joints", title: "Instabilidade", desc: "Torções repetidas e insegurança para caminhar em pisos irregulares." },
      { icon: "pain", title: "Artrose ou impacto", desc: "Desgaste ou alterações mecânicas que causam dor e rigidez." },
    ],
    proceduresTitle: "Condutas para dor no pé e tornozelo",
    proceduresCopy: "O plano combina diagnóstico, controle da dor, orientação de carga e retorno progressivo às atividades.",
    procedures: [
      { icon: "doctor", title: "Avaliação do pé e tornozelo", desc: "Exame da pisada, mobilidade, estabilidade, dor localizada e análise de exames." },
      { icon: "health-worker-form", title: "Orientação de carga", desc: "Ajustes para caminhada, treino, trabalho em pé, calçados e retorno gradual." },
      { icon: "medical-search", title: "Investigação de entorses", desc: "Avaliação ligamentar para dor persistente, instabilidade e torções repetidas." },
      { icon: "injection-care", title: "Procedimentos quando indicados", desc: "Infiltrações e procedimentos podem ser avaliados em casos selecionados." },
    ],
    when: ["Dor ao pisar por mais de 1 a 2 semanas", "Inchaço persistente após torção", "Torções repetidas ou sensação de instabilidade", "Dor no calcanhar ao acordar", "Dor no tendão de Aquiles ou na sola do pé", "Dificuldade para caminhar, correr ou trabalhar em pé"],
    faq: [
      { q: "Dor no calcanhar pode ser fascite plantar?", a: "Pode, especialmente quando piora nos primeiros passos do dia, mas a avaliação é necessária." },
      { q: "Torção de tornozelo precisa de avaliação?", a: "Sim, principalmente se houver inchaço, dor persistente, dificuldade para apoiar ou torções repetidas." },
      { q: "Toda dor no pé é problema de pisada?", a: "Não. Pode envolver fáscia plantar, tendões, ligamentos, ossos ou articulações." },
      { q: "Posso continuar treinando com dor?", a: "Depende do diagnóstico e intensidade. A avaliação define ajustes e retorno seguro." },
      { q: "Infiltração pode ser indicada?", a: "Em casos selecionados, procedimentos podem ser discutidos conforme diagnóstico e objetivo terapêutico." },
    ],
    finalCta: "Não deixe a dor no pé ou tornozelo limitar sua pisada.",
  },
};

export const REGION_SLUGS = Object.keys(REGIONS);
